# Generated by Django 4.2 on 2023-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_directmessage_doc_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/%Y/%m/%d'),
        ),
    ]
