# Generated by Django 4.2 on 2023-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_description', models.TextField(max_length=500)),
                ('register_img', models.ImageField(upload_to='')),
                ('login_description', models.TextField(max_length=500)),
                ('login_img', models.ImageField(upload_to='')),
                ('forget_password_description', models.TextField(max_length=500)),
                ('forget_password_img', models.ImageField(upload_to='')),
                ('home_description', models.TextField(max_length=500)),
                ('home_img', models.ImageField(upload_to='')),
                ('profile_description', models.TextField(max_length=500)),
                ('profile_img', models.ImageField(upload_to='')),
                ('edit_profile_description', models.TextField(max_length=500)),
                ('edit_profile_img', models.ImageField(upload_to='')),
                ('message_description', models.TextField(max_length=500)),
                ('message_img', models.ImageField(upload_to='')),
                ('post_description', models.TextField(max_length=500)),
                ('post_img', models.ImageField(upload_to='')),
                ('comment_description', models.TextField(max_length=500)),
                ('comment_img', models.ImageField(upload_to='')),
                ('vote_description', models.TextField(max_length=500)),
                ('vote_img', models.ImageField(upload_to='')),
                ('relation_description', models.TextField(max_length=500)),
                ('relation_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WebManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_description', models.TextField(max_length=500)),
                ('register_img', models.ImageField(upload_to='')),
                ('login_description', models.TextField(max_length=500)),
                ('login_img', models.ImageField(upload_to='')),
                ('forget_password_description', models.TextField(max_length=500)),
                ('forget_password_img', models.ImageField(upload_to='')),
                ('home_description', models.TextField(max_length=500)),
                ('home_img', models.ImageField(upload_to='')),
                ('profile_description', models.TextField(max_length=500)),
                ('profile_img', models.ImageField(upload_to='')),
                ('edit_profile_description', models.TextField(max_length=500)),
                ('edit_profile_img', models.ImageField(upload_to='')),
                ('message_description', models.TextField(max_length=500)),
                ('message_img', models.ImageField(upload_to='')),
                ('post_description', models.TextField(max_length=500)),
                ('post_img', models.ImageField(upload_to='')),
                ('comment_description', models.TextField(max_length=500)),
                ('comment_img', models.ImageField(upload_to='')),
                ('vote_description', models.TextField(max_length=500)),
                ('vote_img', models.ImageField(upload_to='')),
                ('relation_description', models.TextField(max_length=500)),
                ('relation_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
