# Generated by Django 4.2 on 2023-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemanual',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_comment_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='edit_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_edit_profile_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='forget_password_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_password_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='home_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_home_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='login_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_login_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='message_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_edit_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_post_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_edit_profile_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='register_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_register_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='relation_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_relation_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mobilemanual',
            name='vote_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_vote_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_comment_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='edit_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_edit_profile_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='forget_password_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_password_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='home_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_home_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='login_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_login_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='message_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_edit_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_post_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_profile_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='register_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_register_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='relation_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_relation_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webmanual',
            name='vote_img',
            field=models.ImageField(blank=True, null=True, upload_to='web_vote_img/%Y/%m/%d'),
        ),
    ]
