# Generated by Django 4.2 on 2023-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanual', '0008_adminpanelmanual_admin_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanelmanual',
            name='item_description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='adminpanelmanual',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_login_img/%Y/%m/%d'),
        ),
    ]
